server:
    tomcat:
        accesslog:
            enabled: true
            directory: logs/bingimglog

spring:
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/bingimg?characterEncoding=UTF-8
        username: bingimguser
        password: 840210
        testWhileIdle: true
        testOnBorrow: true
        testOnConnect: true
        validationQuery: select 1

bing:
    img-path: d:/bingimg/
    img-url: http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&mkt=zh-cn